-- Core schema: employees, their salaries (in local currency), and the
-- currency-to-USD rate table used to normalise salaries for comparison.

CREATE TABLE currency_rates (
    currency    VARCHAR(3)     PRIMARY KEY,
    rate_to_usd NUMERIC(18, 6) NOT NULL
);

CREATE TABLE employees (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    email      VARCHAR(255) NOT NULL UNIQUE,
    country    VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    job_title  VARCHAR(150) NOT NULL,
    join_date  DATE         NOT NULL
);

CREATE TABLE salaries (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id    BIGINT        NOT NULL REFERENCES employees (id),
    amount         NUMERIC(15, 2) NOT NULL,
    currency       VARCHAR(3)    NOT NULL REFERENCES currency_rates (currency),
    effective_date DATE          NOT NULL
);

-- Indexes on the columns the employee list filters by and the insights group by.
CREATE INDEX idx_employees_country ON employees (country);
CREATE INDEX idx_employees_department ON employees (department);
CREATE INDEX idx_salaries_employee_id ON salaries (employee_id);
